# Generated by Django 4.1.7 on 2023-02-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hashcode', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('content', models.TextField()),
                ('courseEn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_en', to='form.course')),
                ('courseEs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_es', to='form.course')),
                ('coursePt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_pt', to='form.course')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_1', models.CharField(max_length=200)),
                ('language_2', models.CharField(max_length=200)),
                ('answer_1', models.IntegerField()),
                ('answer_2', models.IntegerField()),
                ('answer_3', models.IntegerField()),
                ('answer_4', models.IntegerField()),
                ('answer_5', models.IntegerField()),
                ('lesson_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_lesson_1', to='form.lesson')),
                ('lesson_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_lesson_2', to='form.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.user')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.course')),
            ],
        ),
    ]
