# Generated by Django 4.1.7 on 2023-02-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_name_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashcode',
            field=models.TextField(),
        ),
    ]
