# Generated by Django 4.1.7 on 2023-02-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_user_hashcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='courseEn',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_en', to='form.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='courseEs',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_es', to='form.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='coursePt',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_pt', to='form.course'),
        ),
    ]
