# Generated by Django 4.1.7 on 2023-02-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_lesson_courseen_alter_lesson_coursees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='courseEn',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_en', to='form.courseen'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='courseEs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_es', to='form.coursees'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='coursePt',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_pt', to='form.coursept'),
        ),
    ]
