# Generated by Django 4.1.7 on 2023-02-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_lesson_courseen_alter_lesson_coursees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='lesson_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_lesson_1', to='form.lesson'),
        ),
        migrations.AlterField(
            model_name='form',
            name='lesson_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_lesson_2', to='form.lesson'),
        ),
    ]
